### ISSUE TITLE
Simplified version of the main example raises Exception

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#19]
If we remove the regularizer and nonnegativity condition from the example in the README, we get:

```python
from proximal import *
import numpy as np
import scipy.misc
import matplotlib.pyplot as plt

# Generate data.
I = scipy.misc.ascent()
np.random.seed(1)
b = I + 10*np.random.randn(*I.shape)

# Construct and solve problem.
x = Variable( I.shape )
prob = Problem(sum_squares(x - b/255))  #  REMOVED: + .1*norm1( grad(x) ) + nonneg(x)
prob.solve()

# Plot the original, noisy, and denoised images.
plt.figure(figsize=(15,8))
plt.subplot(131)
plt.gray()
plt.imshow(I)
plt.title('Original image')

plt.subplot(132)
plt.gray()
plt.imshow(b)
plt.title('Noisy image')

plt.subplot(133)
plt.gray()
plt.imshow(x.value*255) # x.value is the optimal value of x.
plt.title('Denoising results')
plt.show()
```

I get an error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\github\proximal\proximal\algorithms\problem.py", line 96, in solve
    prox_fns = absorb.absorb_all_lin_ops(prox_fns)
  File "e:\github\proximal\proximal\algorithms\absorb.py", line 21, in absorb_all_lin_ops
    ready = prox_funcs[:]
TypeError: 'sum_squares' object has no attribute '__getitem__'
```

The problem can be partially fixed by adding square brackets (`[  ]`) around the argument to `proximal.Problem`, but then another issue appears:

```python
from proximal import *
import numpy as np
import scipy.misc
import matplotlib.pyplot as plt

# Generate data.
I = scipy.misc.ascent()
np.random.seed(1)
b = I + 10*np.random.randn(*I.shape)

# Construct and solve problem.
x = Variable( I.shape )
prob = Problem( [ sum_squares(x - b/255) ] )  #  ADDED [  ]
prob.solve()

# Plot the original, noisy, and denoised images.
plt.figure(figsize=(15,8))
plt.subplot(131)
plt.gray()
plt.imshow(I)
plt.title('Original image')

plt.subplot(132)
plt.gray()
plt.imshow(b)
plt.title('Noisy image')

plt.subplot(133)
plt.gray()
plt.imshow(x.value*255) # x.value is the optimal value of x.
plt.title('Denoising results')
plt.show()
```

I get an error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\github\proximal\proximal\algorithms\problem.py", line 123, in solve
    Knorm = est_CompGraph_norm(K, try_fast_norm=self.try_fast_norm)
  File "e:\github\proximal\proximal\lin_ops\comp_graph.py", line 273, in est_CompGraph_norm
    Knorm = np.sqrt(eigs(A, k=1, M=None, sigma=None, which='LM', tol=tol)[0].real)
  File "C:\Anaconda\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1224, in eigs
    % (k, n - 1))
ValueError: k=1 must be between 1 and ndim(A)-1=-1
```

Tried on windows 7 with python 2.7 and the latest version of proximal from master.

**Comment by SteveDiamond** [comment]
This is fixed.
