### ISSUE TITLE
initializing subsample in 1d

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#22]
Initializing a `proximal.subsample` in 1d seems to have harsher requirements on the input than for example `Variable`:

```python
>>> x = proximal.Variable(4)
>>> proximal.subsample(x, 2)  # this fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\github\proximal\proximal\lin_ops\subsample.py", line 12, in __init__
    shape = tuple([(dim - 1) // step + 1 for dim, step in zip(arg.shape, steps)])
TypeError: zip argument #2 must support iteration
>>> proximal.subsample(x, [2])  # this works
```

**Comment by SteveDiamond** [comment]
This is fixed.
