### ISSUE TITLE
OpenCV dependency missing

### ISSUE THREAD

**Issue by adler-j** [comp-imaging/ProxImaL#26]
When running `pip install proximal` you get an error:

```
>>> import proximal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "proximal/__init__.py", line 3, in <module>
    from .prox_fns import *
  File "proximal/prox_fns/__init__.py", line 1, in <module>
    from .prox_fn import ProxFn
  File "proximal/prox_fns/prox_fn.py", line 4, in <module>
    from proximal.utils import Impl
  File "proximal/utils/__init__.py", line 1, in <module>
    from .utils import Impl
  File "proximal/utils/utils.py", line 6, in <module>
    import cv2
ImportError: No module named cv2
```

It seems some `cv2` binding has to be added to the list of dependencies.

Edit:

I installed [opencv-python](https://pypi.python.org/pypi/opencv-python/3.1.0.3) via `pip install opencv-python` and it works great for me. So that binding can be added.

**Comment by SteveDiamond** [comment]
I added ``opencv-python`` as a dependency in setup.py. This is a much easier way to install the binding then I knew about!
