### ISSUE TITLE
comp_graph.py: np.float(Knorm) is deprecated

### ISSUE THREAD

**Issue by antonysigma** [comp-imaging/ProxImaL#85]
Issue reported by @shnaqvi :

```python
Traceback (most recent call last):
  File "examples/test_deconv_sv_psf.py", line 75, in <module>
    prob.solve(solver='pc', max_iters=2, verbose=True, x0=im.copy())
  File "../../../../../.pyenv/versions/3.10.1/lib/python3.10/site-packages/proximal/algorithms/problem.py", line 156, in solve
    Knorm = est_CompGraph_norm(K, try_fast_norm=self.try_fast_norm)
  File "../../../../../.pyenv/versions/3.10.1/lib/python3.10/site-packages/proximal/lin_ops/comp_graph.py", line 433, in est_CompGraph_norm
    return np.float(Knorm)
  File "../../../../../.pyenv/versions/3.10.1/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

However, the `master` branch indicates the bug is already resolved:

https://github.com/comp-imaging/ProxImaL/blob/3437814f70b45669aab5a44f7da02ee2da5751db/proximal/lin_ops/comp_graph.py#L433

**Comment by antonysigma** [comment]
Confirmed it is a discrepancy between GitHub version and pip version. Closing.
